const titleString = 'Number Trivia';
const captionString = 'Start searching!';
const hintString = 'Input a number';
const searchButtonString = 'SEARCH';
const randomButtonString = 'GET RANDOM TRIVIA';
const knowMoreButtonString = 'KNOW MORE';
const backButtonString = 'BACK';
const wrongInputFormatExceptionString = 'Wrong input format!';
const serverErrorExceptionString = 'Server error! Please check your internet connection or try again later.';
